version: '3.8'
services:
  database:
    image: postgres:18
    container_name: pg-orm
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data: